name: Feature Request
description: File a feature request
title: "[Feature]: "
body:
    - type: markdown
      attributes:
          value: |
              ## Thanks for taking the time to fill out this feature request!

              We love to hear any and all ideas that you may have. It would be great to get as much detail from you as you wish to provide.
    - type: textarea
      attributes:
          label: Tell us about your idea
          description: |
              - Give as much detail as you can to help us understand the change you want to see.
              - What is the expected outcome?
    - type: textarea
      attributes:
          label: Anything else?
          description: |
              Links? References? Anything that will give us more context.
              Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
